# Generated by Django 5.2.13 on 2026-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('head_teacher', 'Head Teacher'), ('academic_master', 'Academic Master'), ('teacher', 'Teacher'), ('secretary', 'Secretary / Receptionist'), ('cashier', 'Cashier'), ('accountant', 'Accountant / Bursar'), ('librarian', 'Librarian'), ('hostel_manager', 'Hostel Manager'), ('transport_manager', 'Transport Manager'), ('stock_keeper', 'Stock Keeper'), ('admin_staff', 'Admin Staff'), ('support_staff', 'Support Staff')], default='teacher', max_length=40),
        ),
    ]
