# Generated by Django 5.2.13 on 2026-05-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='fee_item',
            field=models.ForeignKey(blank=True, help_text='Optional. Select the fee item this payment is paying for.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.studentinvoiceitem'),
        ),
    ]
