# Generated by Django 5.2.13 on 2026-05-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('head_teacher', 'Head Teacher'), ('academic_master', 'Academic Master'), ('secretary', 'Secretary / Receptionist'), ('cashier', 'Cashier'), ('accountant', 'Accountant / Bursar'), ('teacher', 'Teacher'), ('librarian', 'Librarian'), ('hostel_manager', 'Hostel Manager'), ('transport_manager', 'Transport Manager'), ('stock_keeper', 'Stock Keeper'), ('parent', 'Parent / Guardian'), ('support_staff', 'Support Staff')], default='support_staff', max_length=40)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('must_change_password', models.BooleanField(default=False)),
                ('is_active_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
