# Generated by Django 5.2.13 on 2026-04-30 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category_type', models.CharField(choices=[('incident', 'Incident'), ('reward', 'Reward'), ('warning', 'Warning'), ('other', 'Other')], default='incident', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Discipline Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('incident', 'Incident'), ('warning', 'Warning'), ('reward', 'Reward'), ('follow_up', 'Follow Up')], default='incident', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(default=django.utils.timezone.now)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='discipline/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='discipline.disciplinecategory')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_discipline_records', to='staff.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='students.student')),
            ],
            options={
                'ordering': ['-incident_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('next_action', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_followups', to='staff.staffprofile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='discipline.disciplinerecord')),
            ],
            options={
                'ordering': ['-follow_up_date', '-id'],
            },
        ),
    ]
