# Generated by Django 5.2.13 on 2026-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('staff', '0002_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('staff', 'month', 'year'), name='unique_staff_payroll_per_month'),
        ),
    ]
