# Generated by Django 5.2.13 on 2026-05-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('payroll', '0002_alter_payrollrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_record', to='expenses.expense'),
        ),
    ]
