# Generated by Django 5.2.13 on 2026-04-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('school_type', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('both', 'Primary & Secondary')], default='both', max_length=20)),
                ('school_mode', models.CharField(choices=[('day', 'Day School'), ('boarding', 'Boarding School'), ('both', 'Day & Boarding')], default='day', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Profile',
                'verbose_name_plural': 'School Profile',
            },
        ),
    ]
