# Generated by Django 5.2.13 on 2026-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('manager_name', models.CharField(blank=True, max_length=120)),
                ('is_main_branch', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_currency', models.CharField(default='TZS', max_length=10)),
                ('academic_year_auto_create', models.BooleanField(default=False)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('enable_parent_portal', models.BooleanField(default=False)),
                ('enable_student_portal', models.BooleanField(default=False)),
                ('attendance_mode', models.CharField(choices=[('manual', 'Manual Attendance'), ('biometric', 'Biometric Attendance'), ('both', 'Manual & Biometric')], default='manual', max_length=20)),
                ('receipt_prefix', models.CharField(default='RCPT', max_length=30)),
                ('invoice_prefix', models.CharField(default='INV', max_length=30)),
                ('admission_prefix', models.CharField(default='SLA', max_length=30)),
                ('low_stock_alert_level', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
