# Generated by Django 5.2.13 on 2026-04-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('advanced', 'Advanced Secondary')], default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('subject_type', models.CharField(choices=[('compulsory', 'Compulsory'), ('optional', 'Optional')], default='compulsory', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('class_levels', models.ManyToManyField(blank=True, related_name='subjects', to='academics.classlevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.classlevel')),
            ],
            options={
                'ordering': ['class_level__order', 'name'],
                'unique_together': {('class_level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3'), ('semester_1', 'Semester 1'), ('semester_2', 'Semester 2')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear')),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('academic_year', 'name')},
            },
        ),
    ]
